name: Ridibooks Auto-Rental

on:
  schedule:
    - cron: '0 */3 * * *'  # 3시간마다 실행 (UTC 기준)

jobs:
  rent_chapters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install selenium
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest
          install-chromedriver: true
      - name: Run script
        env:
          RIDIBOOKS_USERNAME: ${{ secrets.RIDIBOOKS_USERNAME }}
          RIDIBOOKS_PASSWORD: ${{ secrets.RIDIBOOKS_PASSWORD }}
        run: python rent_chapters.py
